- name: Build Android APK
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: 33
                  target: google_apis
                  arch: x86_64
                  script: ./gradlew assembleRelease

            - name: Upload APK artifact
              uses: actions/upload-artifact@v3
              with:
                  name: RTABMapApp
                  path: app/build/outputs/apk/release/app-release.apk
